# Setup
title:        Reactive blog
tagline:      Disovering Reactive systems
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Thomas Kleinendorst
  url:        http://kleinendorst.eu 

# Gems
gems:
  - jekyll-paginate

# Theme
theme: jekyll-theme-cayman

#Others
markdown: kramdown

# Comments
comments:
  provider: disqus
disqus:
  short_name: kleinendorst-github-io